import { useCallback, useEffect, useState } from 'react'
import { createCoupon, deactivateCoupon, getCoupons, updateCoupon } from '../../services/couponService'

const filters = ['', 'Active', 'Inactive', 'Expired', 'Scheduled', 'Usage Exhausted']
const empty = { coupon_code: '', discount_type: 'Percentage', discount_value: '', valid_from: '', valid_to: '', usage_limit: '' }
const badge = { Active: 'text-bg-success', Inactive: 'text-bg-secondary', Expired: 'text-bg-danger', Scheduled: 'text-bg-info', 'Usage Exhausted': 'text-bg-warning' }
const message = (error) => !error.response ? 'Backend server is currently unavailable.' : error.response.data?.message || 'Something went wrong.'
const date = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'
const inputDate = (value) => value ? new Date(value).toISOString().slice(0, 16) : ''

function CouponForm({ coupon, onClose, onSaved }) {
  const [form, setForm] = useState(coupon ? { ...coupon, valid_from: inputDate(coupon.valid_from), valid_to: inputDate(coupon.valid_to) } : empty)
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const change = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = async (event) => {
    event.preventDefault(); const value = Number(form.discount_value); const limit = Number(form.usage_limit)
    if (!form.coupon_code.trim()) return setError('Coupon code is required.')
    if (!(value > 0) || (form.discount_type === 'Percentage' && value > 100)) return setError('Enter a valid discount value.')
    if (!Number.isInteger(limit) || limit <= 0) return setError('Usage limit must be a positive whole number.')
    if (new Date(form.valid_to) <= new Date(form.valid_from)) return setError('Valid to must be later than valid from.')
    setSaving(true); setError('')
    try { const payload = { ...form, coupon_code: form.coupon_code.trim(), discount_value: value, usage_limit: limit }; const response = coupon ? await updateCoupon(coupon.coupon_id, payload) : await createCoupon(payload); onSaved(response.data.message) } catch (requestError) { setError(message(requestError)); setSaving(false) }
  }
  return <div className="modal-backdrop-wrapper" role="dialog" aria-modal="true"><div className="modal d-block"><div className="modal-dialog modal-dialog-centered"><div className="modal-content"><form onSubmit={submit}><div className="modal-header"><h2 className="modal-title fs-5">{coupon ? 'Edit Coupon' : 'Add Coupon'}</h2><button type="button" className="btn-close" onClick={onClose} /></div><div className="modal-body">{error && <div className="alert alert-danger">{error}</div>}
    <div className="mb-3"><label className="form-label">Coupon Code *</label><input name="coupon_code" className="form-control text-uppercase" maxLength="50" value={form.coupon_code} onChange={change} required /></div>
    <div className="row g-3 mb-3"><div className="col-sm-6"><label className="form-label">Discount Type *</label><select name="discount_type" className="form-select" value={form.discount_type} onChange={change}><option>Percentage</option><option>Fixed</option></select></div><div className="col-sm-6"><label className="form-label">Discount Value *</label><div className="input-group"><span className="input-group-text">{form.discount_type === 'Percentage' ? '%' : '₹'}</span><input name="discount_value" type="number" min="0.01" max={form.discount_type === 'Percentage' ? 100 : undefined} step="0.01" className="form-control" value={form.discount_value} onChange={change} required /></div></div></div>
    <div className="mb-3"><label className="form-label">Valid From *</label><input name="valid_from" type="datetime-local" className="form-control" value={form.valid_from} onChange={change} required /></div><div className="mb-3"><label className="form-label">Valid To *</label><input name="valid_to" type="datetime-local" className="form-control" value={form.valid_to} onChange={change} required /></div><div><label className="form-label">Usage Limit *</label><input name="usage_limit" type="number" min="1" step="1" className="form-control" value={form.usage_limit} onChange={change} required /></div>
  </div><div className="modal-footer"><button type="button" className="btn btn-outline-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Saving...' : 'Save Coupon'}</button></div></form></div></div></div><div className="modal-backdrop show" /></div>
}

export default function CouponDashboard() {
  const [coupons, setCoupons] = useState([]); const [filter, setFilter] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [formCoupon, setFormCoupon] = useState(undefined); const [showForm, setShowForm] = useState(false); const [target, setTarget] = useState(null)
  const load = useCallback(async () => { setLoading(true); setError(''); try { setCoupons((await getCoupons(filter)).data.data) } catch (requestError) { setError(message(requestError)) } finally { setLoading(false) } }, [filter])
  useEffect(() => { getCoupons(filter).then((response) => setCoupons(response.data.data)).catch((requestError) => setError(message(requestError))).finally(() => setLoading(false)) }, [filter])
  const complete = async (text) => { setShowForm(false); setTarget(null); setSuccess(text); await load() }
  const deactivate = async () => { try { const response = await deactivateCoupon(target.coupon_id); await complete(response.data.message) } catch (requestError) { setError(message(requestError)); setTarget(null) } }
  return <section className="container-fluid px-3 px-lg-5 py-4 py-lg-5"><div className="d-flex justify-content-between align-items-start mb-4"><div><h1 className="h2 mb-1">Coupon & Discount Management</h1><p className="text-secondary mb-0">Create, schedule, and manage checkout discounts.</p></div><button className="btn btn-primary" onClick={() => { setFormCoupon(undefined); setShowForm(true) }}>+ Add Coupon</button></div>
    <div className="alert alert-info py-2 small">This dashboard is admin-oriented. Secure admin authorization requires a future authentication and RBAC module.</div>{success && <div className="alert alert-success">{success}</div>}{error && <div className="alert alert-danger">{error}</div>}
    <div className="d-flex flex-wrap gap-2 mb-3">{filters.map((entry) => <button key={entry || 'All'} className={`btn btn-sm ${filter === entry ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setFilter(entry)}>{entry || 'All'}</button>)}</div>
    <div className="card border-0 shadow-sm"><div className="card-body p-0">{loading ? <p className="p-5 text-center text-secondary">Loading coupons...</p> : !coupons.length ? <p className="p-5 text-center text-secondary">No coupons found.</p> : <div className="table-responsive"><table className="table table-hover align-middle mb-0"><thead className="table-light"><tr><th>ID</th><th>Code</th><th>Type</th><th>Value</th><th>Valid From</th><th>Valid To</th><th>Usage</th><th>Status</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{coupons.map((coupon) => <tr key={coupon.coupon_id}><td>{coupon.coupon_id}</td><td className="fw-semibold">{coupon.coupon_code}</td><td>{coupon.discount_type}</td><td>{coupon.discount_type === 'Percentage' ? `${Number(coupon.discount_value)}%` : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(coupon.discount_value)}</td><td>{date(coupon.valid_from)}</td><td>{date(coupon.valid_to)}</td><td>{coupon.used_count} / {coupon.usage_limit}</td><td><span className={`badge ${badge[coupon.display_status]}`}>{coupon.display_status}</span></td><td>{date(coupon.created_at)}</td><td>{date(coupon.updated_at)}</td><td><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-primary" onClick={() => { setFormCoupon(coupon); setShowForm(true) }}>Edit</button>{coupon.status ? <button className="btn btn-sm btn-outline-danger" onClick={() => setTarget(coupon)}>Deactivate</button> : null}</div></td></tr>)}</tbody></table></div>}</div></div>
    {showForm && <CouponForm coupon={formCoupon} onClose={() => setShowForm(false)} onSaved={complete} />}{target && <div className="modal-backdrop-wrapper"><div className="modal d-block"><div className="modal-dialog modal-dialog-centered"><div className="modal-content"><div className="modal-header"><h2 className="modal-title fs-5">Deactivate Coupon</h2></div><div className="modal-body">Are you sure you want to deactivate coupon <strong>{target.coupon_code}</strong>?</div><div className="modal-footer"><button className="btn btn-outline-secondary" onClick={() => setTarget(null)}>Cancel</button><button className="btn btn-danger" onClick={deactivate}>Deactivate</button></div></div></div></div><div className="modal-backdrop show" /></div>}
  </section>
}
